### ISSUE TITLE
App/lib Generator bugs and issues

### ISSUE THREAD

**Issue by samatechtw** [samatechtw/nx-vue3-vite#34]
Various generator issues. Some of these can be addressed in conjunction with #3, since there ought to be tests.

### Tasks

- [ ] Add `@nrwl/jest` and `typescript` to `ProjectDevDependencies` and `LibraryDevDependencies` in `defaults.ts`
- [ ] Add `"moduleResolution": "node"` and `"resolveJsonModule": true` to the app's generated tsconfig
  - Also include `"module": "ESNext"` if the app is generated in a package monorepo
- [ ] Figure out how to handle missing `tsconfig.base.json` in package monorepo
- [ ] Add `postcss.config.js` to library generator

### Notes

Previous notes on app/lib generate issues, some may already be resolved.

**App**
- Favicon should be served from `/public`, instead of `/src/public/favicon.png`
- Remove `name` from components script (maybe only `App.vue`)
- Add to `vite.config.ts` - `'@cypress-local/': `${path.resolve(__dirname, './cypress')}/`,`

**Lib**
- Directory flag not handled correctly. Currently the directory overrides the lib's root folder name, but it should be `<directory>/<lib-name>`
- Missing `cypress.json`
- <strike>Update `jest.config.ts`</strike>
- <strike>Missing `postcss.config.js` (only needed for build?)</strike>

**App & Lib**
- <strike>Remove `'^.+\\.vue$': './deps/vue3-jest',` transform from `jest.config.ts`</strike>
- <strike>eslint.js: `'no-unused-vars': 'off',`</strike>
- Cypress support/plugin typescript files get transformed to js

**Comment by abemscac** [comment]
Hi @samatechtw

Here are some issues I encountered while trying out `nx-vue3-vite`. I'll include my current solution here as well (more like workaround 😬):

- `nx g nx-vue3-vite:app` throws an error `Cannot find module '@nrwl/jest'`. Installing `@nrwl/jest` seems to solve this issue.
- `nx g nx-vue3-vite:library` throws an error `Cannot find module 'typescript'`. Installing `@nrwl/node` seems to solve this issue. This also happened when I `nx serve` the docs and apps generated by `nx-vue3-vite`.
- The following properties need to be added in the `tsconfig.json` generated by `nx g nx-vue3-vite:app` to make TypeScript errors gone:
  - `"moduleResolution": "node"`
  - `"resolveJsonModule": true`: this one is for the json import in `i18n.ts`.
  - `"module": "ESNext"`: this one is for `import.meta`.

**Comment by sampullman** [comment]
Thanks! I'll need to go through this issue to see which of the original problems still apply, but there are a few things which can be solved right away. I'll update the description to include the first and third problems you found.

> (Only in package-based monorepo) nx g nx-vue3-vite:library throws an error Cannot find module 'typescript'. Installing @nrwl/node seems to solve this issue. This also happened when I nx serve the docs and apps generated by nx-vue3-vite.

That's odd, but I think it can be solved by including the `typescript` package in the app/lib dev dependencies. I assumed this would automatically be installed by nx (I think it was in the past), but it seems like that's not the case now.

> (Only in package-based monorepo) npx create-nx-workspace@latest will not create a tsconfig.base.json in the root folder when we choose package-based monorepo; so the "extends": "../../tsconfig.base.json" in app/tsconfig.json throws an error.

This one needs some research, maybe there's an easy way to detect the monorepo type with some helper in `@nrwl/devkit`. If it's a package monorepo, I'm not sure if the correct approach is to create the `tsconfig.base.json` ourselves or to include all the configuration in the app/lib tsconfig.
